# CHINO, ES TU PARTE
print(
'''
XDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXD
XDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXD
XDXD              XDXD    XDXDXD    XDXD              XDXD    XDXDXD    XDXD              XDXD
XDXD    XDXDXDXDXDXDXD    XDXDXD    XDXDXDXDX    XDXDXDXDX      XDXD    XDXD    XDXDXD    XDXD
XDXD    XDXDXDXDXDXDXD    XDXDXD    XDXDXDXDX    XDXDXDXDX    X  XDX    XDXD    XDXDXD    XDXD
XDXD    XDXDXDXDXDXDXD    XDXDXD    XDXDXDXDX    XDXDXDXDX    XD  DX    XDXD    XDXDXD    XDXD
XDXD    XDXDXDXDXDXDXD              XDXDXDXDX    XDXDXDXDX    XD  DX    XDXD    XDXDXD    XDXD
XDXD    XDXDXDXDXDXDXD    XDXDXD    XDXDXDXDX    XDXDXDXDX    XD  XD    XDXD    XDXDXD    XDXD
XDXD    XDXDXDXDXDXDXD    XDXDXD    XDXDXDXDX    XDXDXDXDX    XDX  X    XDXD    XDXDXD    XDXD
XDXD    XDXDXDXDXDXDXD    XDXDXD    XDXDXDXDX    XDXDXDXDX    XDXD      XDXD    XDXDXD    XDXD
XDXD              XDXD    XDXDXD    XDXD              XDXD    XDXDXD    XDXD              XDXD
XDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXD
XDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXD

''')
        